spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/logistics_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:SaiSneha23}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.jwt.secret=${JWT_SECRET:TXlTdXBlclNlY3JldEtleUZvckp3dEF1dGhlbnRpY2F0aW9uMTIzNDU2Nzg5MDEyMzQ1Ng==}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}